apiVersion: apps/v1
kind: Deployment
metadata:
  name: slides-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: react-slides
        image: marbrex/react-slides:linux-arm64
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: slides-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slides-ingress
spec:
  defaultBackend:
    service:
      name: slides-service
      port:
        number: 80

